# Generated by Django 2.2.16 on 2023-03-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230320_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Здесь можно загрузить картинку для своей записи', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
