# Generated by Django 2.2.16 on 2023-03-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230321_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку для своей записи', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
