# Generated by Django 2.2.16 on 2023-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Будьте взаимовежливы', verbose_name='Добавить комментарий'),
        ),
    ]
