# Generated by Django 2.2.16 on 2023-04-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20230328_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Будьте взаимовежливы', verbose_name='Комментарий'),
        ),
    ]
